//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace film
{
    using System;
    using System.Collections.Generic;
    
    public partial class Film
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public System.DateTime ProductionYear { get; set; }
        public string Prizes { get; set; }
        public int CategoryID { get; set; }
        public int ActorID { get; set; }
        public int DirectorID { get; set; }
    
        public virtual Actor Actor { get; set; }
        public virtual Category Category { get; set; }
        public virtual Director Director { get; set; }
    }
}
